import fs from 'node:fs';
import os from 'node:os';
import { spawn, execSync, ChildProcess } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { createInterface } from 'node:readline';
import { WebSocket } from 'ws';

// .env ファイルの自動読み込み (Node 20+ 標準機能 or 簡易パーサー)
function loadEnv() {
  const envPaths = [
    path.resolve(process.cwd(), '.env'),
    path.resolve(process.cwd(), '../..', '.env')
  ];
  for (const envPath of envPaths) {
    if (fs.existsSync(envPath)) {
      try {
        if (typeof (process as any).loadEnvFile === 'function') {
          (process as any).loadEnvFile(envPath);
        } else {
          const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
          for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#')) continue;
            const eqIdx = trimmed.indexOf('=');
            if (eqIdx > 0) {
              const key = trimmed.substring(0, eqIdx).trim();
              const val = trimmed.substring(eqIdx + 1).trim().replace(/^['"]|['"]$/g, '');
              if (!process.env[key]) {
                process.env[key] = val;
              }
            }
          }
        }
        break;
      } catch (e) {
        // ignore
      }
    }
  }
}
loadEnv();

const isWindows = process.platform === 'win32';

// Linux / macOS 環境で PATH を自動拡張（~/.local/bin や node バイナリのディレクトリを自動追加）
function augmentPath() {
  const delimiter = isWindows ? ';' : ':';
  const existing = (process.env.PATH || '').split(delimiter).filter(Boolean);
  const nodeBinDir = path.dirname(process.execPath);
  
  const extras = isWindows ? [] : [
    nodeBinDir,
    path.join(os.homedir(), '.local', 'bin'),
    path.join(os.homedir(), '.npm-global', 'bin'),
    '/usr/local/bin',
    '/usr/bin',
    '/bin'
  ];

  for (const p of extras) {
    if (fs.existsSync(p) && !existing.includes(p)) {
      existing.unshift(p);
    }
  }
  process.env.PATH = existing.join(delimiter);
}
augmentPath();

/**
 * 大文字小文字を問わずに環境変数を取得
 */
function getEnvCaseInsensitive(...keys: string[]): string | undefined {
  for (const k of keys) {
    if (process.env[k] !== undefined && process.env[k] !== '') {
      return process.env[k];
    }
  }
  for (const [envKey, val] of Object.entries(process.env)) {
    for (const k of keys) {
      if (envKey.toLowerCase() === k.toLowerCase() && val !== undefined && val !== '') {
        return val;
      }
    }
  }
  return undefined;
}

/**
 * パス文字列のチルダ (~) 展開とクォート除去
 */
function sanitizePath(raw: string): string {
  let cleaned = raw.trim().replace(/^['"]|['"]$/g, '');
  if (cleaned.startsWith('~/') || cleaned === '~') {
    cleaned = path.join(os.homedir(), cleaned.slice(1));
  }
  return cleaned;
}

/**
 * 実行環境 (Windows / Linux / macOS) に適した Claude Code バイナリパスを解決
 */
function resolveClaudeBin(): { binPath: string; exists: boolean; status: string } {
  const rawEnv = getEnvCaseInsensitive('CLAUDE_BIN', 'claude_bin');

  if (rawEnv) {
    const cleaned = sanitizePath(rawEnv);
    // 非Windows環境で誤って .cmd や .bat が指定されている場合は設定ミスとして自動フォールバック
    if (!isWindows && (cleaned.endsWith('.cmd') || cleaned.endsWith('.bat'))) {
      console.warn(`[Agent] ⚠️ 環境変数で '${rawEnv}' が指定されていますが、非Windows環境 (${process.platform}) のため無視し、Linux/macOS 向けバイナリを自動探索します。`);
    } else {
      const exists = fs.existsSync(cleaned);
      return {
        binPath: cleaned,
        exists,
        status: exists ? '環境変数指定 (有効)' : `⚠️ 環境変数指定 (ファイルが存在しません: ${cleaned})`
      };
    }
  }

  if (isWindows) {
    return { binPath: 'claude.cmd', exists: true, status: 'Windows デフォルト (claude.cmd)' };
  }

  // Linux / macOS: ~/.local/bin/claude, /usr/local/bin/claude 等を探索
  const candidates = [
    path.join(os.homedir(), '.local', 'bin', 'claude'),
    path.join(os.homedir(), '.npm-global', 'bin', 'claude'),
    '/usr/local/bin/claude',
    '/usr/bin/claude'
  ];

  // nvm 配下のパスも探索
  try {
    const nvmDir = path.join(os.homedir(), '.nvm', 'versions', 'node');
    if (fs.existsSync(nvmDir)) {
      const versions = fs.readdirSync(nvmDir);
      for (const v of versions.reverse()) {
        candidates.push(path.join(nvmDir, v, 'bin', 'claude'));
      }
    }
  } catch {}

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return { binPath: candidate, exists: true, status: `自動検出 (${candidate})` };
    }
  }

  // which claude を試行
  try {
    const whichRes = execSync('which claude 2>/dev/null', { encoding: 'utf-8' }).trim();
    if (whichRes && fs.existsSync(whichRes)) {
      return { binPath: whichRes, exists: true, status: `which コマンドによる検出 (${whichRes})` };
    }
  } catch {}

  return { binPath: 'claude', exists: false, status: '⚠️ 未検出 (PATH または候補パスに見つかりません)' };
}

const HUB_URL = process.env.HUB_URL || 'ws://localhost:8090/ws/agent';
// 明示的に AUTH_TOKEN が指定されている場合はそれを尊重、未指定なら衝突しない一意なランダムUUIDを自動生成
const isAutoGeneratedToken = !process.env.AUTH_TOKEN;
const AUTH_TOKEN = process.env.AUTH_TOKEN || randomUUID();
const claudeInfo = resolveClaudeBin();
const CLAUDE_BIN = claudeInfo.binPath;
const currentDir = process.cwd();
const isAgentDir = path.basename(currentDir) === 'agent' || currentDir.endsWith(path.join('packages', 'agent'));
const DEFAULT_CWD = process.env.DEFAULT_CWD || (isAgentDir ? path.resolve(currentDir, '../..') : currentDir);
const HOSTNAME = process.env.HOSTNAME || process.env.COMPUTERNAME || os.hostname() || 'OfficePC';

let ws: WebSocket | null = null;
let reconnectTimer: NodeJS.Timeout | null = null;
let currentChildProcess: ChildProcess | null = null;
const knownSessions = new Set<string>();

/**
 * Hub URL からスマホ PWA のアクセス・ペアリング URL を推定生成
 */
function getPwaPairingUrl(hubUrl: string, token: string): string {
  try {
    const parsed = new URL(hubUrl);
    const isWss = parsed.protocol === 'wss:';
    const httpProto = isWss ? 'https:' : 'http:';
    let basePath = parsed.pathname.replace(/\/ws\/agent\/?$/, '');
    if (!basePath.endsWith('/')) basePath += '/';
    return `${httpProto}//${parsed.host}${basePath}?token=${encodeURIComponent(token)}`;
  } catch {
    return `?token=${encodeURIComponent(token)}`;
  }
}

const pairingUrl = getPwaPairingUrl(HUB_URL, AUTH_TOKEN);

console.log('======================================================================');
console.log('🚀 AI Remote Bridge Agent Started');
console.log('======================================================================');
console.log(`💻 Hostname      : ${HOSTNAME}`);
console.log(`📂 Default CWD   : ${DEFAULT_CWD}`);
console.log(`🌐 Target Hub    : ${HUB_URL}`);
console.log(`🤖 Claude Binary : ${CLAUDE_BIN}`);
console.log(`   状態          : ${claudeInfo.status}`);
if (!claudeInfo.exists && !isWindows) {
  console.log('');
  console.log('⚠️ 【注意】Claude Code CLI が見つかりませんでした！');
  console.log('   ・インストール確認: which claude');
  console.log('   ・未インストールの場合は実行: npm install -g @anthropic-ai/claude-code');
  console.log('   ・または .env に絶対パスを指定: CLAUDE_BIN=/home/<user>/.../claude (チルダ ~ は不可)');
}
console.log(`🔑 Session Token : ${AUTH_TOKEN}${isAutoGeneratedToken ? ' (自動発行UUID)' : ' (環境変数指定)'}`);
console.log('');
console.log('📱 スマホで開いて即ペアリング (URLクエリで自動設定):');
console.log(`   ${pairingUrl}`);
console.log('');
console.log('※ PC起動ごとに一意なトークンが自動発行され、複数人でも混線せず安全に利用可能です。');
console.log('======================================================================');

/**
 * Hub への WebSocket 接続を確立
 */
function connectToHub() {
  if (reconnectTimer) {
    clearTimeout(reconnectTimer);
    reconnectTimer = null;
  }

  const url = `${HUB_URL}?token=${encodeURIComponent(AUTH_TOKEN)}`;
  console.log(`[Agent] Connecting to Hub at ${HUB_URL}...`);
  ws = new WebSocket(url);

  ws.on('open', () => {
    console.log('[Agent] Successfully connected to Relay Hub!');
    
    // Agent 初期情報を Hub (および接続中 Client) へ送信
    sendToHub({
      type: 'agent_hello',
      hostname: HOSTNAME,
      defaultCwd: DEFAULT_CWD,
      timestamp: new Date().toISOString()
    });
  });

  ws.on('message', (data) => {
    try {
      const msg = JSON.parse(data.toString());
      handleClientMessage(msg);
    } catch (err: any) {
      console.error('[Agent] Failed to parse message from Hub:', err.message);
    }
  });

  ws.on('close', (code, reason) => {
    console.warn(`[Agent] Disconnected from Hub (${code}: ${reason.toString()}). Reconnecting in 3s...`);
    ws = null;
    scheduleReconnect();
  });

  ws.on('error', (err) => {
    console.error('[Agent] WebSocket error:', err.message);
  });
}

function scheduleReconnect() {
  if (!reconnectTimer) {
    reconnectTimer = setTimeout(connectToHub, 3000);
  }
}

function sendToHub(payload: any) {
  if (ws && ws.readyState === WebSocket.OPEN) {
    ws.send(JSON.stringify(payload));
  }
}

/**
 * 社内PC上のワークスペース/プロジェクト候補を走査
 */
function scanProjects(customRoot?: string) {
  const scanDir = customRoot || process.env.PROJECTS_ROOT || path.resolve(DEFAULT_CWD, '..');
  const projects: Array<{ id: string; name: string; path: string; isGit: boolean }> = [];

  try {
    if (fs.existsSync(scanDir)) {
      const entries = fs.readdirSync(scanDir, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
          const fullPath = path.join(scanDir, entry.name);
          const isGit = fs.existsSync(path.join(fullPath, '.git'));
          projects.push({
            id: entry.name,
            name: entry.name,
            path: fullPath,
            isGit
          });
        }
      }
    }
  } catch (err: any) {
    console.error('[Agent] Failed to scan projects directory:', err.message);
  }

  // もし DEFAULT_CWD が候補に含まれていなければ先頭に追加
  const currentName = path.basename(DEFAULT_CWD);
  if (!projects.some(p => p.path === DEFAULT_CWD)) {
    projects.unshift({
      id: currentName,
      name: currentName,
      path: DEFAULT_CWD,
      isGit: fs.existsSync(path.join(DEFAULT_CWD, '.git'))
    });
  }

  return {
    baseDir: scanDir,
    projects
  };
}

/**
 * Client からのメッセージ処理
 */
function handleClientMessage(msg: any) {
  console.log('[Agent] Received from Client:', msg.type);

  if (msg.type === 'prompt') {
    executeClaudeTurn(msg);
  } else if (msg.type === 'abort') {
    abortCurrentTurn();
  } else if (msg.type === 'get_status') {
    sendToHub({
      type: 'agent_status',
      hostname: HOSTNAME,
      cwd: DEFAULT_CWD,
      isBusy: currentChildProcess !== null,
      timestamp: new Date().toISOString()
    });
  } else if (msg.type === 'list_projects') {
    const result = scanProjects(msg.rootPath);
    sendToHub({
      type: 'projects_list',
      baseDir: result.baseDir,
      projects: result.projects,
      timestamp: new Date().toISOString()
    });
  } else {
    console.log('[Agent] Unhandled message type:', msg.type);
  }
}

/**
 * 現在実行中の Claude プロセスを中断
 */
function abortCurrentTurn() {
  if (currentChildProcess) {
    console.log('[Agent] Aborting current Claude process...');
    currentChildProcess.kill('SIGINT');
    sendToHub({
      type: 'execution_aborted',
      timestamp: new Date().toISOString()
    });
  }
}

/**
 * Claude Code の 1 ターンを実行
 */
function executeClaudeTurn(params: {
  text: string;
  sessionId?: string;
  isResume?: boolean;
  cwd?: string;
  permissionMode?: string;
}) {
  if (currentChildProcess) {
    sendToHub({
      type: 'error',
      message: 'Claude Code is already running a task. Please wait or abort.',
      code: 'BUSY'
    });
    return;
  }

  const prompt = params.text;
  const activeSessionId = params.sessionId || randomUUID();
  // isResume が明示されていなければ knownSessions にあるか判定（未記録なら初回なので false）
  const initialResume = params.isResume !== undefined
    ? params.isResume
    : Boolean(params.sessionId && knownSessions.has(params.sessionId));
  const workDir = params.cwd || DEFAULT_CWD;
  const permissionMode = params.permissionMode || 'acceptEdits';

  const runProcess = (resumeMode: boolean) => {
    const args: string[] = [
      '-p',
      prompt,
      '--output-format=stream-json',
      '--include-partial-messages',
      '--verbose',
      `--permission-mode=${permissionMode}`
    ];

    if (resumeMode) {
      args.push('--resume', activeSessionId);
    } else {
      args.push('--session-id', activeSessionId);
    }

    console.log(`[Agent] Launching Claude: ${CLAUDE_BIN} ${args.join(' ')}`);
    console.log(`[Agent] Session ID: ${activeSessionId} (isResume: ${resumeMode})`);
    console.log(`[Agent] Working dir: ${workDir}`);

    sendToHub({
      type: 'turn_start',
      prompt,
      sessionId: activeSessionId,
      cwd: workDir,
      timestamp: new Date().toISOString()
    });

    let hasOutput = false;
    let resumeNotFound = false;

    const child = spawn(CLAUDE_BIN, args, {
      cwd: workDir,
      env: {
        ...process.env,
        FORCE_COLOR: '0'
      },
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: isWindows
    });

    currentChildProcess = child;
    let capturedSessionId = activeSessionId;

    // stdout を 1 行ずつ JSON パースして Hub へ転送
    const readlineStdout = createInterface({ input: child.stdout });
    readlineStdout.on('line', (line) => {
      const trimmed = line.trim();
      if (!trimmed) return;

      try {
        const event = JSON.parse(trimmed);
        hasOutput = true;

        if (event.session_id && !capturedSessionId) {
          capturedSessionId = event.session_id;
        }
        knownSessions.add(capturedSessionId);

        sendToHub({
          type: 'claude_event',
          sessionId: capturedSessionId,
          event
        });
      } catch (err) {
        console.warn('[Agent] Non-JSON stdout line:', trimmed);
        sendToHub({
          type: 'claude_raw_log',
          stream: 'stdout',
          text: trimmed
        });
      }
    });

    // stderr の収集
    const readlineStderr = createInterface({ input: child.stderr });
    readlineStderr.on('line', (line) => {
      console.warn('[Agent] stderr:', line);
      if (line.includes('No conversation found with session ID')) {
        resumeNotFound = true;
      }
      sendToHub({
        type: 'claude_raw_log',
        stream: 'stderr',
        text: line
      });
    });

    child.on('close', (code, signal) => {
      console.log(`[Agent] Claude process exited with code ${code}, signal ${signal}`);
      currentChildProcess = null;

      // もし --resume で過去セッションが見つからずに即終了した場合、--session-id で自動フォールバック再試行！
      if (resumeMode && resumeNotFound && !hasOutput) {
        console.warn(`[Agent] Session ${activeSessionId} not found to resume. Falling back to fresh --session-id...`);
        knownSessions.delete(activeSessionId);
        runProcess(false);
        return;
      }

      if (code === 0) {
        knownSessions.add(capturedSessionId);
      }

      sendToHub({
        type: 'turn_end',
        sessionId: capturedSessionId,
        exitCode: code,
        signal,
        timestamp: new Date().toISOString()
      });
    });

    child.on('error', (err: any) => {
      console.error('[Agent] Failed to spawn Claude process:', err);
      currentChildProcess = null;

      let errorDetail = err.message;
      if (err.code === 'ENOENT') {
        errorDetail = `Claude Code CLI ('${CLAUDE_BIN}') が見つかりません (ENOENT)。\n` +
          `【考えられる原因と対処】\n` +
          `1. パスにチルダ (~) が使われていた場合は /home/<ユーザー>/... のフル絶対パスで指定してください。\n` +
          `2. 環境変数は大文字で 'CLAUDE_BIN' と指定してください。\n` +
          `3. Claude Code が未インストールの場合は 'npm install -g @anthropic-ai/claude-code' を実行してください。\n` +
          `4. 確認用: ターミナルで 'which claude' または 'ls -la ${CLAUDE_BIN}' を実行してください。`;
      }

      sendToHub({
        type: 'turn_error',
        error: errorDetail,
        timestamp: new Date().toISOString()
      });
    });
  };

  try {
    runProcess(initialResume);
  } catch (err: any) {
    console.error('[Agent] Execution exception:', err);
    currentChildProcess = null;
    sendToHub({
      type: 'turn_error',
      error: err.message,
      timestamp: new Date().toISOString()
    });
  }
}

// 起動
connectToHub();

// プロセス終了時のクリーンアップ
process.on('SIGINT', () => {
  if (currentChildProcess) {
    currentChildProcess.kill('SIGINT');
  }
  if (ws) {
    ws.close();
  }
  process.exit(0);
});
